CREATE DATABASE IF NOT EXISTS sims;
USE sims;

CREATE TABLE Users (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE SecurityQuestions (
  SQ_ID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Question VARCHAR(255) NOT NULL,
  Answer VARCHAR(255) NOT NULL,
  FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE Spare_Part (
  SpareP_ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(150) NOT NULL,
  Category VARCHAR(100) NOT NULL,
  Quantity INT NOT NULL DEFAULT 0,
  UnityPrice DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  TotalPrice DECIMAL(10,2) GENERATED ALWAYS AS (Quantity * UnityPrice) STORED
);

CREATE TABLE Stock_In (
  StockIn_ID INT AUTO_INCREMENT PRIMARY KEY,
  SpareP_ID INT NOT NULL,
  StockInQuantity INT NOT NULL,
  StockInDate DATE NOT NULL,
  FOREIGN KEY (SpareP_ID) REFERENCES Spare_Part(SpareP_ID) ON DELETE CASCADE
);

CREATE TABLE Stock_Out (
  StockOut_ID INT AUTO_INCREMENT PRIMARY KEY,
  SpareP_ID INT NOT NULL,
  StockOutQuantity INT NOT NULL,
  StockOutUnitPrice DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  StockOutTotalPrice DECIMAL(10,2) GENERATED ALWAYS AS (StockOutQuantity * StockOutUnitPrice) STORED,
  StockOutDate DATE NOT NULL,
  FOREIGN KEY (SpareP_ID) REFERENCES Spare_Part(SpareP_ID) ON DELETE CASCADE
);
